function out1 = dphideq(in1)
%DPHIDEQ
%    OUT1 = DPHIDEQ(IN1)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-10-16 14:35:12

out1 = reshape([3.0e+2,0.0,0.0,0.0,0.0,0.0,0.0,3.0e+2,0.0,0.0,0.0,0.0,0.0,0.0,3.0e+2,0.0,0.0,0.0,0.0,0.0,0.0,3.0e+2,0.0,0.0,0.0,0.0,0.0,0.0,3.0e+2,0.0,0.0,0.0,0.0,0.0,0.0,3.0e+2],[6,6]);
end
