function out1 = dVdq(q1,q2)
%dVdq
%    OUT1 = dVdq(Q1,Q2)

%    This function was generated by the Symbolic Math Toolbox version 23.2.
%    2024-10-11 14:51:32

t2 = q1+q2;
t3 = cos(t2);
t4 = t3.*(4.9e+1./1.0e+1);
out1 = [t4+cos(q1).*(1.47e+2./1.0e+1);t4];
end
